### PR TITLE
Ungroup is sent to the single speaker instead of the master

### LINKED ISSUE #46: sonos party_mode fails to group 3 speakers
On OS 10.9 (ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]) and 3 Sonos devices (Play 1, Playbar, and Play 3):

```
08:59 ~$ sonos devices
BRIDGE              10.0.1.100
Kitchen             10.0.1.119
Living Room         10.0.1.101
Dining Room         10.0.1.104
```

Party mode seems to always group 2 of them, but fails to group the third and gives an error:

```
08:59 ~$ sonos party_mode
/Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/response.rb:85:in `raise_soap_and_http_errors!': (s:Client) UPnPError (Savon::SOAPFault)
	from /Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/response.rb:14:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/operation.rb:64:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/operation.rb:64:in `create_response'
	from /Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/operation.rb:55:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/savon-2.7.2/lib/savon/client.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/endpoint/a_v_transport.rb:262:in `send_transport_message'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/endpoint/a_v_transport.rb:252:in `set_av_transport_uri'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/endpoint/a_v_transport.rb:220:in `join'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/system.rb:43:in `block in party_mode'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/system.rb:41:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/system.rb:41:in `party_mode'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/lib/sonos/cli.rb:32:in `party_mode'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/sonos-0.3.6/bin/sonos:7:in `<top (required)>'
	from /usr/bin/sonos:23:in `load'
	from /usr/bin/sonos:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by masone**
commands in AVTransport are sent to the group master by default. this is correct for most commands, like `play` for example. sending the `ungroup` command to the master results in removing the master from the group instead of the referenced speaker. 

I guess it is also open for discussion if other commands are falsely sent to the master. 
Might also fix #46 since the `party_mode` does a `party_over` which does not properly `ungroup` the existing speakers.

### CODE REVIEW

**Comment by masone** [comment]
@gotwalt ping

**Comment by gotwalt** [comment]
👍  - apologies for the lag.

**Comment by masone** [comment]
No big deal, thanks for taking the time

**Comment by gotwalt** [comment]
Will bump the version and cut a new gem later today. 

On Tue, Jun 28, 2016 at 8:02 AM -0700, "Christian Felder" notifications@github.com wrote:

No big deal, thanks for taking the time

**Pull request merged**
